### ISSUE TITLE
used TF.Keras

### ISSUE THREAD

**Issue by sonfire186** [CyberZHG/keras-lookahead#9]
How can I use TF.Keras?

**Comment by herosunly** [comment]
I also encounter this problem.

**Comment by sonfiree** [comment]
so far i just deleted the keras selection conditions

**Comment by herosunly** [comment]
> so far i just deleted the keras selection conditions

Run sucessfully?

**Comment by CyberZHG** [comment]
Add `TF_KERAS=1` to your environment variables.

**Comment by sonfiree** [comment]
> > so far i just deleted the keras selection conditions
> 
> Run sucessfully?


Yes it works for me.



> Add `TF_KERAS=1` to your environment variables.


Unfortunately this does not work
